using System.ComponentModel.DataAnnotations;

namespace TournamentTool.Enums;

public enum MinecraftAdvancement
{
    // ====== Story Advancements ======
    [Display(Name = "Minecraft", Description = "story.root", ShortName = "story")] StoryRoot,
    [Display(Name = "Stone Age", Description = "story.mine_stone", ShortName = "mine_stone")] StoryMineStone,
    [Display(Name = "Getting an Upgrade", Description = "story.upgrade_tools", ShortName = "upgrade_tools")] StoryUpgradeTools,
    [Display(Name = "Acquire Hardware", Description = "story.smelt_iron", ShortName = "smelt_iron")] StorySmeltIron,
    [Display(Name = "Suit Up", Description = "story.obtain_armor", ShortName = "obtain_armor")] StoryObtainArmor,
    [Display(Name = "Hot Stuff", Description = "story.lava_bucket", ShortName = "lava_bucket")] StoryLavaBucket,
    [Display(Name = "Isn't It Iron Pick", Description = "story.iron_tools", ShortName = "iron_tools")] StoryIronTools,
    [Display(Name = "Not Today, Thank You", Description = "story.deflect_arrow", ShortName = "deflect_arrow")] StoryDeflectArrow,
    [Display(Name = "Ice Bucket Challenge", Description = "story.form_obsidian", ShortName = "form_obsidian")] StoryFormObsidian,
    [Display(Name = "Diamonds!", Description = "story.mine_diamond", ShortName = "mine_diamond")] StoryMineDiamond,
    [Display(Name = "We Need to Go Deeper", Description = "story.enter_the_nether", ShortName = "enter_the_nether")] StoryEnterTheNether,
    [Display(Name = "Cover Me with Diamonds", Description = "story.shiny_gear", ShortName = "shiny_gear")] StoryShinyGear,
    [Display(Name = "Enchanter", Description = "story.enchant_item", ShortName = "enchant_item")] StoryEnchantItem,
    [Display(Name = "Zombie Doctor", Description = "story.cure_zombie_villager", ShortName = "cure_zombie_villager")] StoryCureZombieVillager,
    [Display(Name = "Eye Spy", Description = "story.follow_ender_eye", ShortName = "follow_ender_eye")] StoryFollowEnderEye,
    [Display(Name = "The End?", Description = "story.enter_the_end", ShortName = "enter_the_end")] StoryEnterTheEnd,

    // ====== Nether Advancements ======
    [Display(Name = "Nether", Description = "nether.root", ShortName = "nether")] NetherRoot,
    [Display(Name = "Return to Sender", Description = "nether.return_to_sender", ShortName = "return_to_sender")] NetherReturnToSender,
    [Display(Name = "Those Were the Days", Description = "nether.find_bastion", ShortName = "find_bastion")] NetherFindBastion,
    [Display(Name = "Hidden in the Depths", Description = "nether.obtain_ancient_debris", ShortName = "obtain_ancient_debris")] NetherObtainAncientDebris,
    [Display(Name = "Subspace Bubble", Description = "nether.fast_travel", ShortName = "fast_travel")] NetherFastTravel,
    [Display(Name = "A Terrible Fortress", Description = "nether.find_fortress", ShortName = "find_fortress")] NetherFindFortress,
    [Display(Name = "Who is Cutting Onions?", Description = "nether.obtain_crying_obsidian", ShortName = "obtain_crying_obsidian")] NetherObtainCryingObsidian,
    [Display(Name = "Oh Shiny", Description = "nether.distract_piglin", ShortName = "distract_piglin")] NetherDistractPiglin,
    [Display(Name = "This Boat Has Legs", Description = "nether.ride_strider", ShortName = "ride_strider")] NetherRideStrider,
    [Display(Name = "Uneasy Alliance", Description = "nether.uneasy_alliance", ShortName = "uneasy_alliance")] NetherUneasyAlliance,
    [Display(Name = "War Pigs", Description = "nether.loot_bastion", ShortName = "loot_bastion")] NetherLootBastion,
    [Display(Name = "Country Lode, Take Me Home", Description = "nether.use_lodestone", ShortName = "use_lodestone")] NetherUseLodestone,
    [Display(Name = "Cover Me in Debris", Description = "nether.netherite_armor", ShortName = "netherite_armor")] NetherNetheriteArmor,
    [Display(Name = "Spooky Scary Skeleton", Description = "nether.get_wither_skull", ShortName = "get_wither_skull")] NetherGetWitcherSkull,
    [Display(Name = "Into Fire", Description = "nether.obtain_blaze_rod", ShortName = "obtain_blaze_rod")] NetherObtainBlazeRod,
    [Display(Name = "Not Quite \"Nine\" Lives", Description = "nether.charge_respawn_anchor", ShortName = "charge_respawn_anchor")] NetherChargeRespawnAnchor,
    [Display(Name = "Feels Like Home", Description = "nether.ride_strider_in_overworld_lava", ShortName = "ride_strider_in_overworld_lava")] NetherRiderStriderInOverworldLava,
    [Display(Name = "Hot Tourist Destinations", Description = "nether.explore_nether", ShortName = "explore_nether")] NetherExploreNether,
    [Display(Name = "Withering Heights", Description = "nether.summon_wither", ShortName = "summon_wither")] NetherSummonWither,
    [Display(Name = "Local Brewery", Description = "nether.brew_potion", ShortName = "brew_potion")] NetherBrewPotion,
    [Display(Name = "Bring Home the Beacon", Description = "nether.create_beacon", ShortName = "create_beacon")] NetherCreateBeacon,
    [Display(Name = "A Furious Cocktail", Description = "nether.all_potions", ShortName = "all_potions")] NetherAllPotions,
    [Display(Name = "Beaconator", Description = "nether.create_full_beacon", ShortName = "create_full_beacon")] NetherCreateFullBeacon,
    [Display(Name = "How Did We Get Here?", Description = "nether.all_effects", ShortName = "all_effects")] NetherAllEffects,

    // ====== The End Advancements ======
    [Display(Name = "The End", Description = "end.root", ShortName = "end")] EndRoot,
    [Display(Name = "Free the End", Description = "end.kill_dragon", ShortName = "kill_dragon")] EndKillDragon,
    [Display(Name = "The Next Generation", Description = "end.dragon_egg", ShortName = "dragon_egg")] EndDragonEgg,
    [Display(Name = "Remote Getaway", Description = "end.enter_end_gateway", ShortName = "enter_end_gateway")] EndEnterEndGateway,
    [Display(Name = "The End... Again...", Description = "end.respawn_dragon", ShortName = "respawn_dragon")] EndRespawnDragon,
    [Display(Name = "You Need a Mint", Description = "end.dragon_breath", ShortName = "dragon_breath")] EndDragonBreath,
    [Display(Name = "The City at the End of the Game", Description = "end.find_end_city", ShortName = "find_end_city")] EndFindEndCity,
    [Display(Name = "Sky's the Limit", Description = "end.elytra", ShortName = "elytra")] EndElytra,
    [Display(Name = "Great View From Up Here", Description = "end.levitate", ShortName = "levitate")] EndLevitate,

    // ====== Adventure Advancements =======
    [Display(Name = "Adventure", Description = "adventure.root", ShortName = "adventure")] AdventureRoot,
    [Display(Name = "Voluntary Exile", Description = "adventure.voluntary_exile", ShortName = "voluntary_exile")] AdventureVoluntaryExile,
    [Display(Name = "Is It a Bird?", Description = "adventure.spyglass_at_parrot", ShortName = "spyglass_at_parrot")] AdventureSpyglassAtParrot,
    [Display(Name = "Monster Hunter", Description = "adventure.kill_a_mob", ShortName = "kill_a_mob")] AdventureKillAMob,
    [Display(Name = "The Power of Books", Description = "adventure.read_power_of_chiseled_bookshelf", ShortName = "read_power_of_chiseled_bookshelf")] AdventureReadPowerOfChiseledBookshelf,
    [Display(Name = "What a Deal!", Description = "adventure.trade", ShortName = "trade")] AdventureTrade,
    [Display(Name = "Crafting a New Look", Description = "adventure.trim_with_any_armor_pattern", ShortName = "trim_with_any_armor_pattern")] AdventureTrimAnyArmor,
    [Display(Name = "Sticky Situation", Description = "adventure.honey_block_slide", ShortName = "honey_block_slide")] AdventureHoneyBlockSlide,
    [Display(Name = "Ol' Betsy", Description = "adventure.ol_betsy", ShortName = "ol_betsy")] AdventureOlBetsy,
    [Display(Name = "Surge Protector", Description = "adventure.lightning_rod_with_villager_no_fire", ShortName = "lightning_rod_with_villager_no_fire")] AdventureLightningRodWithVillagerNoFire,
    [Display(Name = "Caves & Cliffs", Description = "adventure.fall_from_world_height", ShortName = "fall_from_world_height")] AdventureFallFromWorldHeight,
    [Display(Name = "Respecting the Remnants", Description = "adventure.salvage_sherd", ShortName = "salvage_sherd")] AdventureSalvageSherd,
    [Display(Name = "Sneak 100", Description = "adventure.avoid_vibration", ShortName = "avoid_vibration")] AdventureAvoidVibration,
    [Display(Name = "Sweet Dreams", Description = "adventure.sleep_in_bed", ShortName = "sleep_in_bed")] AdventureSleepInBed,
    [Display(Name = "Hero of the Village", Description = "adventure.hero_of_the_village", ShortName = "hero_of_the_village")] AdventureHeroOfTheVillage,
    [Display(Name = "Is It a Balloon?", Description = "adventure.spyglass_at_ghast", ShortName = "spyglass_at_ghast")] AdventureSpyglassAtGhast,
    [Display(Name = "A Throwaway Joke", Description = "adventure.throw_trident", ShortName = "throw_trident")] AdventureThrowTrident,
    [Display(Name = "It Spreads", Description = "adventure.kill_mob_near_sculk_catalyst", ShortName = "kill_mob_near_sculk_catalyst")] AdventureKillMobNearSculkCatalyst,
    [Display(Name = "Take Aim", Description = "adventure.shoot_arrow", ShortName = "shoot_arrow")] AdventureShootArrow,
    [Display(Name = "Monsters Hunted", Description = "adventure.kill_all_mobs", ShortName = "kill_all_mobs")] AdventureKillAllMobs,
    [Display(Name = "Postmortal", Description = "adventure.totem_of_undying", ShortName = "totem_of_undying")] AdventureTotemOfUndying,
    [Display(Name = "Hired Help", Description = "adventure.summon_iron_golem", ShortName = "summon_iron_golem")] AdventureSummonIronGolem,
    [Display(Name = "Star Trader", Description = "adventure.trade_at_world_height", ShortName = "trade_at_world_height")] AdventureTradeAtWorldHeight,
    [Display(Name = "Smithing with Style", Description = "adventure.trim_with_all_exclusive_armor_patterns", ShortName = "trim_with_all_exclusive_armor_patterns")] AdventureTrimWithAllExclusiveArmorPatterns,
    [Display(Name = "Two Birds, One Arrow", Description = "adventure.two_birds_one_arrow", ShortName = "two_birds_one_arrow")] AdventureTwoBirdsOneArrow,
    [Display(Name = "Who's the Pillager Now?", Description = "adventure.whos_the_pillager_now", ShortName = "whos_the_pillager_now")] AdventureWhoThePillagerNow,
    [Display(Name = "Arbalistic", Description = "adventure.arbalistic", ShortName = "arbalistic")] AdventureArbalistic,
    [Display(Name = "Careful Restoration", Description = "adventure.craft_decorated_pot_using_only_sherds", ShortName = "craft_decorated_pot_using_only_sherds")] AdventureCraftDecoratedPotUsingOnlySherds,
    [Display(Name = "Adventuring Time", Description = "adventure.adventuring_time", ShortName = "adventuring_time")] AdventureAdventuringTime,
    [Display(Name = "Sound of Music", Description = "adventure.play_jukebox_in_meadows", ShortName = "play_jukebox_in_meadows")] AdventurePlayJukeboxInMeadows,
    [Display(Name = "Light as a Rabbit", Description = "adventure.walk_on_powder_snow_with_leather_boots", ShortName = "walk_on_powder_snow_with_leather_boots")] AdventureWalOnPowderSnowWithLeatherBoots,
    [Display(Name = "Is It a Plane?", Description = "adventure.spyglass_at_dragon", ShortName = "spyglass_at_dragon")] AdventureSpyglassAtDragon,
    [Display(Name = "Very Very Frightening", Description = "adventure.very_very_frightening", ShortName = "very_very_frightening")] AdventureVeryVeryFrightening,
    [Display(Name = "Sniper Duel", Description = "adventure.sniper_duel", ShortName = "sniper_duel")] AdventureSniperDuel,
    [Display(Name = "Bullseye", Description = "adventure.bullseye", ShortName = "bullseye")] AdventureBullseye,

    // ====== Husbandry Advancements ======
    [Display(Name = "Husbandry", Description = "husbandry.root", ShortName = "husbandry")] HusbandryRoot,
    [Display(Name = "Bee Our Guest", Description = "husbandry.safely_harvest_honey", ShortName = "safely_harvest_honey")] HusbandrySafelyHarvestHoney,
    [Display(Name = "The Parrots and the Bats", Description = "husbandry.breed_an_animal", ShortName = "breed_an_animal")] HusbandryBreedAnAnimal,
    [Display(Name = "You've Got a Friend in Me", Description = "husbandry.allay_deliver_item_to_player", ShortName = "allay_deliver_item_to_player")] HusbandryAllayDeliverItemToPlayer,
    [Display(Name = "Whatever Floats Your Goat!", Description = "husbandry.ride_a_boat_with_a_goat", ShortName = "ride_a_boat_with_a_goat")] HusbandryRideABoatWithAGoat,
    [Display(Name = "Best Friends Forever", Description = "husbandry.tame_an_animal", ShortName = "tame_an_animal")] HusbandryTameAnAnimal,
    [Display(Name = "Glow and Behold!", Description = "husbandry.make_a_sign_glow", ShortName = "make_a_sign_glow")] HusbandryMakeASignGlow,
    [Display(Name = "Fishy Business", Description = "husbandry.fishy_business", ShortName = "fishy_business")] HusbandryFishyBusiness,
    [Display(Name = "Total Beelocation", Description = "husbandry.silk_touch_nest", ShortName = "silk_touch_nest")] HusbandrySilkTouchNest,
    [Display(Name = "Bukkit Bukkit", Description = "husbandry.tadpole_in_a_bucket", ShortName = "tadpole_in_a_bucket")] HusbandryTadpoleInABucket,
    [Display(Name = "Smells Interesting", Description = "husbandry.obtain_sniffer_egg", ShortName = "obtain_sniffer_egg")] HusbandryObtainSnifferEgg,
    [Display(Name = "A Seedy Place", Description = "husbandry.plant_seed", ShortName = "plant_seed")] HusbandryPlantSeed,
    [Display(Name = "Wax On", Description = "husbandry.wax_on", ShortName = "wax_on")] HusbandryWaxOn,
    [Display(Name = "Two by Two", Description = "husbandry.bred_all_animals", ShortName = "bred_all_animals")] HusbandryBredAllAnimals,
    [Display(Name = "Birthday Song", Description = "husbandry.allay_deliver_cake_to_note_block", ShortName = "allay_deliver_cake_to_note_block")] HusbandryAllayDeliverCakeToNoteBlock,
    [Display(Name = "A Complete Catalogue", Description = "husbandry.complete_catalogue", ShortName = "complete_catalogue")] HusbandryCompleteCatalogue,
    [Display(Name = "Tactical Fishing", Description = "husbandry.tactical_fishing", ShortName = "tactical_fishing")] HusbandryTacticalFishing,
    [Display(Name = "When the Squad Hops into Town", Description = "husbandry.leash_all_frog_variants", ShortName = "leash_all_frog_variants")] HusbandryLeashAllFrogVariants,
    [Display(Name = "Little Sniffs", Description = "husbandry.feed_snifflet", ShortName = "feed_snifflet")] HusbandryFeedSnifflet,
    [Display(Name = "A Balanced Diet", Description = "husbandry.balanced_diet", ShortName = "balanced_diet")] HusbandryBalancedDiet,
    [Display(Name = "Serious Dedication", Description = "husbandry.obtain_netherite_hoe", ShortName = "obtain_netherite_hoe")] HusbandryObtainNetheriteHoe,
    [Display(Name = "Wax Off", Description = "husbandry.wax_off", ShortName = "wax_off")] HusbandryWaxOff,
    [Display(Name = "The Cutest Predator", Description = "husbandry.axolotl_in_a_bucket", ShortName = "axolotl_in_a_bucket")] HusbandryAxolotlInABucket,
    [Display(Name = "With Our Powers Combined!", Description = "husbandry.froglights", ShortName = "froglights")] HusbandryFroglights,
    [Display(Name = "Planting the Past", Description = "husbandry.plant_any_sniffer_seed", ShortName = "plant_any_sniffer_seed")] HusbandryPlantAnySnifferSeed,
    [Display(Name = "The Healing Power of Friendship!", Description = "husbandry.kill_axolotl_target", ShortName = "kill_axolotl_target")] HusbandryKillAxolotlTarget,
    
    // Druga czesc jest warta trzymania z racji i tak podzielu na splity
    // ======= Ranked ======
    [Display(Name = "(Ranked) Blind Travel", Description = "projectelo.timeline.blind_travel", ShortName = "blind_travel")] ProjectEloBlindTravel,
    [Display(Name = "(Ranked) Dragon Death", Description = "projectelo.timeline.dragon_death", ShortName = "dragon_death")] ProjectEloDragonDeath,
    [Display(Name = "(Ranked) Forfeit", Description = "projectelo.timeline.forfeit", ShortName = "forfeit")] ProjectEloForfeit,
    [Display(Name = "(Ranked) Complete", Description = "projectelo.timeline.complete", ShortName = "complete")] ProjectEloComplete,
    [Display(Name = "(Ranked) Death", Description = "projectelo.timeline.death", ShortName = "death")] ProjectEloDeath,
    
    // ======= Paceman Splits ======
    [Display(Name = "(Paceman) Obtain iron ingot", Description = "rsg.obtain_iron_ingot", ShortName = "obtain_iron_ingot")] PaceObtainIronIngot,
    [Display(Name = "(Paceman) Obtain iron pickaxe", Description = "rsg.obtain_iron_pickaxe", ShortName = "obtain_iron_pickaxe")] PacemanObtainIronPickaxe,
    [Display(Name = "(Paceman) Obtain lava bucket", Description = "rsg.obtain_lava_bucket", ShortName = "obtain_iron_bucket")] PacemanObtainLavaBucket,
    [Display(Name = "(Paceman) Obtain Obsidian", Description = "rsg.obtain_obsidian", ShortName = "obtain_obsidian")] PacemanObtainObsidian,
    [Display(Name = "(Paceman) Enter nether", Description = "rsg.enter_nether", ShortName = "enter_nether")] PacemanEnterNether,
    [Display(Name = "(Paceman) Enter bastion", Description = "rsg.enter_bastion", ShortName = "enter_bastion")] PacemanEnterBastion,
    [Display(Name = "(Paceman) Enter fortress", Description = "rsg.enter_fortress", ShortName = "enter_fortress")] PacemanEnterFortress,
    [Display(Name = "(Paceman) First portal", Description = "rsg.first_portal", ShortName = "first_portal")] PacemanFirstPortal,
    [Display(Name = "(Paceman) Second portal", Description = "rsg.second_portal", ShortName = "second_portal")] PacemanSecondPortal,
    [Display(Name = "(Paceman) Enter stronghold", Description = "rsg.enter_stronghold", ShortName = "enter_stronghold")] PacemanEnterStronghold,
    [Display(Name = "(Paceman) Enter end", Description = "rsg.enter_end", ShortName = "enter_end")] PacemanEnterEnd,
    [Display(Name = "(Paceman) Credits", Description = "rsg.credits", ShortName = "credits")] PacemanCredits,
}