<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>14</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\TournamentTool.Core\TournamentTool.Core.csproj" />
      <ProjectReference Include="..\TournamentTool.Domain\TournamentTool.Domain.csproj" />
      <ProjectReference Include="..\TournamentTool.Services\TournamentTool.Services.csproj" />
    </ItemGroup>

</Project>
